### ISSUE TITLE
ES5 Compatibility

### ISSUE THREAD

**Issue by neil-morrison44** [stayradiated/google-places-periods-parser#1]
Very useful module - but it looks like the built JS has `const`s & fat arrow functions

Seems to be fairly common that, at least until IE11 dies off, packages which could be used in browser are exported as ES5 - or as full ECMA modules

I'd branch & PR if it was just a config change but I guess it'll require changes to your packager?

I've tried running it through our babel but since it's CommonJS already it doesn't sit well with the EMCA module things also being babel'd, I've seen plugins that go EMCA module -> CommonJS but not the other way around.

A ECMA module export would also be a solution it doesn't make sense to support ES5.

Thanks

**Comment by stayradiated** [comment]
Cheers Neil, I've updated the build config to target ES5. Let me know if there is anything else I can do to help.
